Config
luanlabs/wagent-payment-api pull request #4
Opened 2024-06-20 07:46 UTC by ReihaneENS

add : config

2024-06-21 10:50 UTC, feritka79 requested changes

2024-06-21 10:50 UTC, feritka79 commented on .env
Add this file to the gitignore

2024-06-21 10:50 UTC, feritka79 commented on src/config/config.ts
> +import mongoose from "mongoose";
Change the file name to connectDb.
Use connect ( import { connect } from 'mongoose' )

2024-06-21 10:50 UTC, feritka79 commented on src/config/config.ts
> +    // await mongoose.connect(process.env.DB_URI as string);
use connect ( await connect(url, { dbName }) )
Take uri and dbName as parameters in the function

2024-06-21 10:50 UTC, feritka79 commented on src/env.ts
> +const checkEnvs = ()=>{
Change the function name to getEnvs

2024-06-21 10:50 UTC, feritka79 commented on src/env.ts
> +    enforceEnv(envs)
Use enforceEnv like this:
enforceEnv(envVariables, { returnValues: true });
and return it

2024-06-21 10:50 UTC, feritka79 commented on src/index.ts
> +import connectDB from "./config/config";
Add a blank line here

2024-06-21 10:50 UTC, feritka79 commented on src/index.ts
> +dotenv.config();
remove dotenv.
When using getEnvs, there is no need for dotenv

2024-06-21 10:50 UTC, feritka79 commented on src/index.ts
> +connectDB();
Pass these parameters like this :
const { DB_URI, DB_NAME } = getEnvs();
connectDb(DB_URI,DB_NAME)

2024-06-21 10:50 UTC, feritka79 commented on src/index.ts
> +app.use("/users", userRoutes);
Create a routes folder and add routes there

2024-06-21 10:50 UTC, feritka79 commented on src/index.ts
> +const PORT = process.env.PORT || 5000;
use PORT

const {PORT} = getEnvs()

2024-06-21 10:50 UTC, feritka79 commented on tsconfig.json
> +    "rootDir": "./src",                                /* Specify the root folder within your source files. */
No need for this property

2024-06-21 10:50 UTC, feritka79 commented on tsconfig.json
> +  "exclude": ["node_modules", "**/*.test.ts"]
No need for this property
add property ( "outDir": "./dist")

2024-06-21 11:47 UTC, ceydae commented on src/index.ts
> +app.use("/users", userRoutes);
remove routes for now

2024-06-21 11:56 UTC, ceydae requested changes
Learn about the commit conventions in Notion.

Remove the `route(users)` because in this specific PR, we do not want to handle any routes and our only focus is the base config and files. 

There's also an error when trying to run the project, you should run `npm run build` before any PRs to check if there's anything wrong.

Currently, there's this error:

```
src/index.ts:3:24 - error TS2307: Cannot find module './routes/userRoutes' or its corresponding type declarations.

3 import userRoutes from "./routes/userRoutes";
```

2024-06-21 14:41 UTC, feritka79 requested changes

2024-06-21 14:41 UTC, feritka79 commented on src/index.ts
> +
Modify the above code as follows:
connectDB(DB_URI,  DB_NAME)
app.listen(port, () => {
      console.log(`Server is running on port ${port}`)
});

**Avoid using route in this file**

2024-06-21 14:41 UTC, feritka79 commented on src/index.ts
> +const { DB_URI, DB_NAME } = getEnvs();
Retrieve the PORT here  { DB_URI, DB_NAME , PORT}

2024-06-21 14:41 UTC, feritka79 commented on src/index.ts
> +const {PORT} = getEnvs();
remove this line

2024-06-21 14:41 UTC, feritka79 commented on src/env.ts
> +    return envValues;
Return the function directly.
No need to create a variable

2024-06-25 06:36 UTC, ceydae requested changes

2024-06-25 06:36 UTC, ceydae commented on .env
ignore this file from git

2024-06-25 06:36 UTC, ceydae commented on src/env.ts
rename to src/getEnvs.ts

2024-06-25 06:36 UTC, ceydae commented on src/index.ts
> +        console.error('Failed to connect to the database:', err);
No need to wait for DB to connect and then implement the routes. They can be written separately and asynchronously

2024-06-25 06:36 UTC, ceydae commented on src/index.ts
> +        console.error('Failed to connect to the database:', err);
Like so:

```
connectDB()

app.get()

app.listen()

2024-06-29 12:37 UTC, ceydae commented
No need for connectDB() to have a `.then()` or `.catch()` because they are already handled in the connectDB function.

Also, resolve the conflicts.

2024-06-29 12:57 UTC, merged